### PR TITLE
API: re-organize / split plans.py for developer convenience 

### LINKED ISSUE #850: Split plans module into separate modules
The `plans.py` file is quite large and somewhat difficult to navigate. Typing `bluesky.plans.<TAB>` issues a very long list of suggestions, mixing high-level plans like `count` with low-level plans like `stage_wrapper`. To improve the discoverability, we propose breaking the plans module into:

* `plans.py` -> things like `scan` and `count` that create a run
* ~`plan_parts.py`~ `plan_stubs.py` -> things like `mv`, `trigger_and_read`, `fly` ("stub plans")
* `preprocessors.py` -> the wrappers and decorators that transform a plan into a different plan

For backward-compatibility, we can shim imports into `plans.py` with a warning about the new location.

Thoughts -- @teddyrendahl, @ZLLentz, @hhslepicka, @prjemian?

### PR DESCRIPTION
**Pull request by tacaswell**
This will be force-pushed to

The nominal goal is to get all of the local imports into plans.py namespaced so tab-complete only gives you fully boxed plans.

@teddyrendahl @ZLLentz I suspect this will cause you a lot of breakage.

cntx.py is likely to be deleted, all of it's contents were already deprecated.

closes #850

### CODE REVIEW

**Comment by tacaswell** [comment]
The selling point of these namespace is that you can do

```python
from bluesky import plns as bp
from bluesky import rplns as rbp
```

and then `bp.<tab>` or `rbp.<tab>` gives you reasonable (<15 entry) lists of options to make them discover-able.  

We keep back-api on everything else and if you want to import individually `from bluesky.plans import (count, grid_scan)` you can as well.

I think this is the easiest path to A) not breaking anything B) providing curated namespaces

**Comment by danielballan** [comment]
Yes, but as you know, users who might reasonably see that code you wrote and then try:

```python
from bluesky.plns import scan
from bluesky.rplns import relative_scan
```

may well be surprised to find that they don't work!

What is scans.py? It's midnight before 1.0.0. Let's stick to the plan.

**Comment by tacaswell** [comment]
The point of this whole exercise is to give a nice currated namespace,  if we are going to support the long plan names forever out of `bluesky.plans` the option are either this or making yet another module just to hold some imports.

Scaling those ambitions back to slightly better sorted modules for devs.

**Comment by danielballan** [comment]
>  if we are going to support the long plan names forever out of `bluesky.plans`

As a collaboration, I think we can weight the benefits of a pristine namespace against the cost of slowly retiring the old names. Creating yet-another-namespace -- and one with import behavior that experienced Python users might find surprising -- is not something I want to do unilaterally the night before a release.

**Comment by danielballan** [comment]
The controversial parts of this have been separated off into #896 and marked for consideration for a later release. Thanks, @tacaswell :- )

The scope of this PR is now in line with what folks signed off on in #850. Note that, in that issue, I originally proposed, "we can shim imports into plans.py with a warning about the new location." We have not actually done that here, judging that it would be better to fix the errors than generate a big slew of warnings.

If we have misjudged that, we can always add shims in a quick patch release and then walk the changes out more gradually. But I think we're correctly following the spirit on the consensus in #850.

**Pull request merged**
