### PR TITLE
MNT: Remove too-cute repr for examples objs.

### PR DESCRIPTION
**Pull request by danielballan**
This repr dates back to the original implementation demo, where the RunEngine
printed every message is saw for the purposes of explaining its operation.

The raw repr looks like more like the ones from ophyd and makes a less
confusing example nowadays.

### CODE REVIEW

**Comment by danielballan** [comment]
In case this seems neurotic and unimportant, it came up while writing another batch of examples for NSLS-II/docs. Does that help? :sheep:

**Comment by klauer** [comment]
Not neurotic. I ran into it before with the "too-cute ':' " not quite working with `eval()` (*cough*).

**Comment by danielballan** [comment]
Believe it or not, IIRC this particular repr was a rare effort from @tacaswell to make things *human*-readable. I hate to discourage the impulse, you know? But, yes, in the end it seems it was not the right choice.

**Comment by tacaswell** [comment]
Lesson learned: reading is only for computers.

Probably should replace this with a round-trippable repr

**Comment by klauer** [comment]
`__str__` != `__repr__`

To further waste our time on this: I'd recommend the original `__repr__` becomes `__str__` for readability, and make a new round-trippable `__repr__` as @tacaswell mentions.

**Comment by danielballan** [comment]
Discussed offline -- we will take a different approach, but not soon.

**Pull request closed without merging**
