### PR TITLE
ENH/TST: Make example devices serializable.

### PR DESCRIPTION
**Pull request by danielballan**
The old example devices happened to be serializable. I didn't realize xpdacq was effectively testing on that. This restores serializability and adds a test using dill, now an optional test dependency.

- Built-in pickle won't work in general (can't pickle local functions or
  lambda functions) but other implementations will. Here we test using dill.

attn @chiahaoliu

### CODE REVIEW

**Comment by tacaswell** [comment]
I am skeptical, are real `Device` objects serializable?!

**Comment by danielballan** [comment]
You opened an ophyd issue stating that they should be. Xpdacq is aware that they are not yet.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Sep 8, 2016 at 2:55 PM -0400, "Thomas A Caswell" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am skeptical, are real Device objects serializable?!

**Comment by danielballan** [comment]
Somehow this got merged (awhile ago). Stray commits must have landed on another branch, perhaps a docs-related one. Sorry about that.

Let me know if you want me to pull this out, @tacaswell.

**Comment by tacaswell** [comment]
meh

**Pull request closed without merging**
