### PR TITLE
Test against 3.4 too, since we still have 3.4 installations at some beamlines

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
Kick travis again now that tifffile is being installed

**Comment by tacaswell** [comment]
Apparently we are using my personal anaconda.org for some of the deps...

```
conda install super_state_machine cycler xray-vision lmfit -c tacaswell
```

**Comment by ericdill** [comment]
Yep. That is on my list of things to fix!

**Comment by ericdill** [comment]
restarting travis against current master

**Comment by ericdill** [comment]
@tacaswell @danielballan this is good to go

**Pull request merged**
