### PR TITLE
ENH: ReaderWithFilestore uses its own read

### PR DESCRIPTION
**Pull request by CJ-Wright**
This way `trigger_read` can be overridden to deal with more complex readers
eg readers with shutters

## Motivation and Context
This allows for a more flexible setup, where the data can be modified from the `Reader` after the read but before the data is stashed into FS

## How Has This Been Tested?
I ran the existing tests.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@tacaswell ready for review.

**Comment by CJ-Wright** [comment]
@brookeferber This was the PR I said I'd put in.

**Comment by tacaswell** [comment]
I still have grave reservations about you extending these classes.

**Comment by CJ-Wright** [comment]
I guess my current feeling is that if/when you get rid of bluesky examples I will move the code base to whatever setup you suggest.

**Pull request merged**
