### PR TITLE
ENH: Add PLOT_Y to LiveTable by default.

### PR DESCRIPTION
**Pull request by hhslepicka**
The idea is to insert by default the PLOT_Y to the LiveTable when using the SPEC-like API.

### CODE REVIEW

**Comment by danielballan** [comment]
Does this behave itself if gs.PLOT_Y is already in gs.TABLE_COLS?

**Comment by tacaswell** [comment]
The new version of live table will happily print the same column more than once.

**Comment by hhslepicka** [comment]
@danielballan 
Based on my tests, yes it will.

```python
In [1]: gs.PLOT_Y
Out[1]: 'det'

In [2]: gs.TABLE_COLS
Out[2]: []

In [3]: gs.TABLE_COLS = ['det']

In [4]: ascan(motor, 0, 10, 10)
Scan ID: 25
Unique ID: e9e417a0-b0b5-47fa-aa11-b3f521c09f38
+-----------+------------+------------+------------+
|   seq_num |       time |      motor |        det |
+-----------+------------+------------+------------+
|         1 | 15:26:51.8 |      0.000 |      1.000 |
|         2 | 15:26:51.9 |      1.000 |      0.607 |
|         3 | 15:26:52.0 |      2.000 |      0.135 |
|         4 | 15:26:52.1 |      3.000 |      0.011 |
|         5 | 15:26:52.2 |      4.000 |      0.000 |
|         6 | 15:26:52.3 |      5.000 |      0.000 |
|         7 | 15:26:52.4 |      6.000 |      0.000 |
|         8 | 15:26:52.4 |      7.000 |      0.000 |
|         9 | 15:26:52.5 |      8.000 |      0.000 |
|        10 | 15:26:52.6 |      9.000 |      0.000 |
|        11 | 15:26:52.7 |     10.000 |      0.000 |
+-----------+------------+------------+------------+
AbsScanPlan ['e9e417'] (scan num: 25)
Out[4]: ['e9e417a0-b0b5-47fa-aa11-b3f521c09f38']

In [5]: ophyd.__version__
Out[5]: '0.2.1+12.gbf8ac9e'

In [6]: bluesky.__version__
Out[6]: '0.4.3+13.gf34bca8'

In [7]:
```

**Comment by danielballan** [comment]
I thought I remembered that LiveTable avoided redundancies. Looks like it still does.

**Comment by hhslepicka** [comment]
What about return a set here to avoid this repeated fields issue:
https://github.com/NSLS-II/bluesky/blob/master/bluesky/callbacks/core.py#L212

**Comment by danielballan** [comment]
I don't think a set is exactly right because users might prefer that we respect the order that they choose.

**Comment by hhslepicka** [comment]
So, in this case, what about add a filter before adding to the list of string_fields.

**Comment by danielballan** [comment]
Yes, that sounds right.

**Pull request merged**
