### PR TITLE
Sanitize all docs

### PR DESCRIPTION
**Pull request by arkilic**
Recursively sanitizes documents that are emitted by the RunEngine from np types
## Description

Basically added two functions, one sanitizes the docs from np.generic and np.ndarray and another one that applies this(or any other) function to a doc recursively.

## Motivation and Context

See https://github.com/NSLS-II/bluesky/issues/710

## How Has This Been Tested?

test_utils/test_illegal_np emulates what happened at HXN the other day.

More testing recommendations are welcome.

### CODE REVIEW

**Comment by tacaswell** [comment]
I thought we were going push all of the sanitization to the ingest side and let the RE emit numpy arrays and such?  

#710 is to put this sanitazition into the ZMQ publisher.

**Comment by danielballan** [comment]
Right. This would undo #674. The hope was to make #674 safe to merge by sanitizing on the way _in_ to the Publisher, as you have already sanitized on the way in to metadatastores.

**Comment by stuartcampbell** [comment]
Looks like there's been a little misunderstanding here.  Am I correct in saying that the numpy 'sanitation' will happen for the ZMQ publisher (plus any other future publishers of a similar ilk) and the databroker 'side' ? 

Do we have an issue on the databroker side ?

**Comment by tacaswell** [comment]
We had https://github.com/NSLS-II/databroker/pull/195 which had some bugs and needed a rebase.  I needed the same code for the https://github.com/NSLS-II/databroker/pull/216 so cherry-picked the commits.

**Comment by danielballan** [comment]
@arkilic and I superceded this with a new commit in #674.

**Pull request closed without merging**
