### PR TITLE
add doct to requirements

### PR DESCRIPTION
**Pull request by CJ-Wright**
Imported in `blueksy.callbacks.broker`

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Ready for Review!

**Comment by CJ-Wright** [comment]
done, although I don't really understand the dev vs not dev reqs.

**Comment by tacaswell** [comment]
can you move `attrs` too?

**Comment by mrakitin** [comment]
It's used by travis: https://github.com/NSLS-II/bluesky/blob/7e49f70fe128ac9b8198435b90781f70ee1d7277/.travis.yml#L29. I think the idea was to install bluesky with less dependencies, but if users want full functional, then optional dev dependencies should be installed. @danielballan, @tacaswell, any comments?

**Comment by tacaswell** [comment]
Ohh, I understand this now, never mind.

`requirement` is things you need too run, `dev-requirements` are things you need to run the tests.

We should probably just remove the use of `doct`....

**Comment by danielballan** [comment]
Thanks for addressing this. I agree that we should just remove doct. In light of stated plans for databroker, this should just use plain dicts. (Search for the phrase "custom dictionary" in the [databroker release notes](https://nsls-ii.github.io/databroker/whats_new.html).)

**Comment by CJ-Wright** [comment]
Just for context I ran into this because the conda-forge build of bluesky caused breakages from this missing dep.
@danielballan Is that going to be in the release that goes out to the beamlines?
@mrakitin Would there be any interest in breaking this up a bit more (build, run, test, doc)?

**Comment by mrakitin** [comment]
@CJ-Wright, not sure, maybe not. We tended to merge the requirements. See, e.g. https://github.com/NSLS-II/bluesky/pull/901/files.

**Comment by danielballan** [comment]
@CJ-Wright Yes, in fact that was released last cycle (including at XPD).

**Comment by CJ-Wright** [comment]
I meant if the total removal of doct was going to go into a release this cycle.

**Comment by danielballan** [comment]
Oh, sorry. No, not this cycle. This cycle, we _just_ got some of the more complex beamlines updated to the version of databroker where we deprecated it, so we should let it sit for a cycle or two before full removing.

**Comment by CJ-Wright** [comment]
Can this go in?

**Comment by tacaswell** [comment]
I am :-1: on merging this, will have a PR to just hide the import shortly.

**Comment by danielballan** [comment]
Agreed -- we should just remove doct or hide the import.

**Pull request closed without merging**
