### PR TITLE
ENH : Bec qtbrowser compat

### PR DESCRIPTION
**Pull request by jrmlhermitte**
proposed enhancement for use of db browser
needs #963 first
(this was rebased on 963 right now)
Also, we may want to squash these commits.

### CODE REVIEW

**Comment by tacaswell** [comment]
@jrmlhermitte can you rebase this?

**Comment by jrmlhermitte** [comment]
done. incredibly terse and basically just the modifications you suggested :-)

**Comment by danielballan** [comment]
Squashed locally, merged into master as 2f9122b1b7e1e360e61f7476b5893407313b02d8, pushed.

**Comment by jrmlhermitte** [comment]
thanks @danielballan !

**Pull request closed without merging**
