### PR TITLE
FIX: let BEC plot integers

### PR DESCRIPTION
**Pull request by tacaswell**
The big rewrite is not going to make it out for this release so
make the small fix.

### CODE REVIEW

**Comment by teddyrendahl** [comment]
Closes https://github.com/NSLS-II/bluesky/issues/1097

**Comment by tacaswell** [comment]
sigh, this test relies on an unreleased version of ohpyd to pass.

**Comment by danielballan** [comment]
Confused why Travis passed on this PR but then the merge failed the master branch on what looks like a real error:

https://travis-ci.org/NSLS-II/bluesky/jobs/469751943#L1365-L1384

**Comment by tacaswell** [comment]
see https://github.com/NSLS-II/bluesky/pull/1131 for fix to test race condition.

**Pull request merged**
