### PR TITLE
DEV: Add RE.md['ipython_profile']

### LINKED ISSUE #1049: store ipython profile name in RE metadata
## Expected Behavior
Wouldn't it be nice if ...

the metadata included the name of the ipython profile
for diagnostic purposes, of course

## Current Behavior
doesn't do this

## Possible Solution
I've got code

## Steps to Reproduce (for bugs)
enhancement

## Context
supporting users for when they do not know what went wrong

## Your Environment
any

### PR DESCRIPTION
**Pull request by ke-zhang-rd**
## Motivation and Context

See #1049 for the discussion.

## How Has This Been Tested?

Resolves #1049.

### CODE REVIEW

**Comment by ke-zhang-rd** [comment]
Thanks, updated. Where could I check sphinx render result? @danielballan

**Comment by mrakitin** [comment]
@ke-zhang-rd, you can build the docs locally. For that, go to the `doc` directory at the top level of the repo, and run `make html`. Then you could open the generated `.html` files in your browser to check correctness of the formatting. You may need to install extra-packages to build the docs, but I believe you had already installed [dev-requirements.txt](https://github.com/NSLS-II/bluesky/blob/master/dev-requirements.txt).

**Comment by danielballan** [comment]
Ah, sorry that I totally missed your question @ke-zhang-rd.

**Comment by mrakitin** [comment]
@ke-zhang-rd, FYI, I reopened #1049 to have it automatically being closed once this PR is merged. Please note the `Resolves #1049` in the PR description (I edited it a bit to give more context), that's a special GitHub keyword allowing to automatically close the associated issue.

**Comment by tacaswell** [comment]
Do we need this in light of the suggested use of IPython methods in https://github.com/NSLS-II/bluesky/issues/1049#issuecomment-447949350 ?

**Comment by prjemian** [comment]
Since https://github.com/NSLS-II/bluesky/issues/1049#issuecomment-447949350 describes the implementation best, that's how to add this to RE's metadata.  This issue can be closed.

**Comment by tacaswell** [comment]
If you need this functionality, it is built into IPython

```python
from IPython import get_ipython
RE.md['ipython_profile'] = get_ipython().profile
```

**Pull request closed without merging**
