### PR TITLE
update ramp_plan in plans.py to enable customized choose whether add …

### PR DESCRIPTION
**Pull request by ke-zhang-rd**
…pre data or not

### CODE REVIEW

**Comment by ke-zhang-rd** [comment]
function ramp_plan will automatically add a pre data point. Try fix by give user optional  to choose whether add that or not

**Comment by danielballan** [comment]
Thanks, @ke-zhang-rd. This reinforces my sense that `ramp_plan` has to be _so_ parameterized that it might be better to just rewrite it as needed on a case-by-case basis, but I guess that ship has sailed.

Can we brainstorm possible names? I see what you mean by `pre_data_enable` but I wonder if we can think of something more descriptive, something that might be more obvious to someone who is encountering this function for the first time. Ideas:

* take_initial_point
* initial_datapoint
* take_pre_point

Others?

**Comment by ke-zhang-rd** [comment]
@danielballan 
You mean rewrite ramp_plan?  Make several case-by-case function instead of one parameterized function? 

How about "**take_pre_data**"?

**Comment by danielballan** [comment]
> You mean rewrite ramp_plan? Make several case-by-case function instead of one parameterized function?

Yeah.

> How about "take_pre_data"?

That works for me.

**Comment by ke-zhang-rd** [comment]
@danielballan,
Should I set default as "take_pre_data = True" OR False? 
True might be more compatible to current working code.

**Comment by danielballan** [comment]
Yes, I think it's much better to avoid an API break and default to `True`.

**Comment by ke-zhang-rd** [comment]
thanks @tacaswell 

now ramp_plan is compatible with existing code. If bealine need get rid of pre data, just set it as false? Is that good logic?

Also, what is the workflow of merger pull request? Is that during group meeting?

**Comment by danielballan** [comment]
> If beamline need get rid of pre data, just set it as false? Is that good logic?

Yes

> Also, what is the workflow of merger pull request? Is that during group meeting?

It depends on the PR. Things with a large impact get a lot of review and sign-off from our collaborators at other facilities. Simple changes can be merged once one or two people have had a look.

I am curious -- how did this first come up? From your explorations of `ramp_plan`?

**Comment by ke-zhang-rd** [comment]
No, from one deployment before at IOS. Tom found it.

Should I request someone review it?  since this is a small change

**Comment by danielballan** [comment]
I feel comfortable unilaterally merging this one. Thanks for the improvement!

**Comment by ke-zhang-rd** [comment]
Gotcha.

**Pull request merged**
