### PR TITLE
ENH: Add LiveFit, a callback that integrates with lmfit.

### PR DESCRIPTION
**Pull request by danielballan**
In summary:

``` python
cb = LiveFit(lmfit_model, 'det', {'x': 'motor'}, init_guess)
# ...run a scan...
cb.result  # an lmfit.ModelResult
```

See documentation in this PR for details.

`LiveFit` itself does not introduce an lmfit dependency or any other new dependency -- it expects the user to pass in an lmfit model (or anything that provides that interface) -- so I put it in `bluesky/callbacks/core.py`.

Includes a test and minor adjacent code and docs cleanup.

### CODE REVIEW

**Comment by danielballan** [comment]
This is what the output of `LivePlot` (blue dots) and `LiveFitPlot` (red line) look like when pointed at the same axes:

livefitplot

It might be neat to add a caption that displays the best-fit parameters.

**Comment by tacaswell** [comment]
These tests seem to be hanging / killing the tests on travis.

**Comment by danielballan** [comment]
All tests passed on both 3.4 and 3.5 builds. The 3.4 build finished successfully; the 3.5 build stopped producing output after [py.test completed successfully](https://travis-ci.org/NSLS-II/bluesky/jobs/171976340#L1247).

Merge?

**Comment by hhslepicka** [comment]
Looks good to me! 👍

**Pull request merged**
