### PR TITLE
Replacement to LiveGrid

### PR DESCRIPTION
**Pull request by awalter-bnl**
WORK IN PROGRESS, REQUIRES #1076 BEFORE IT CAN BE TESTED/ USED.
This PR will add a new `Grid` callback, a new `grid_factory` callback factory and potentially a new `path` callback. 

## Description
This will add a replacement to LiveGrid, using the new callback API being added in #1076 and incorporating the changes requested to LiveGrid as detailed in #1095.

## Motivation and Context
It primarily creates a new grid plot that works with the new callbacks mechanism found in #1076. In addition it adds several features requested across the issues #1095, #1039 , #1003, #1001 and #1061. These include: 

- allowing for arbitrary paths through the grid space.
    - This is done through the new function part of the callbacks that allow for more flexibility in the conversion between the data in the event doc and where that is included on the Grid. 
- adding greater flexibility to modify how images are plotted.
    - This is done via the new callback factories and the grid callback API, which allow for any matplotlib kwarg to be passed through to grid
- including the ability to swap axes directions, relative/absolute units and other plotting paths
    - This is done through the new functions for converting between the information in the event docs and where on the grid the data is to be placed.

## How Has This Been Tested?
This has yet to be tested, once PR #1076 is complete then it can be tested and it shouldn't be merged prior to that.

### CODE REVIEW

**Comment by awalter-bnl** [comment]
git issues have been resolved

**Comment by awalter-bnl** [comment]
I have resolved all of the changes requested by @danielballan

**Comment by awalter-bnl** [comment]
@danielballan I was able to change the target branch to NSLS-II/one-run-callbacks but so far am unable to change it to danielballan/one-run-callbacks. The google search I did indicated that this was only possible between branches in the same repo, not between repos. I would rather not open a new PR and loose the comment history here, but if you insist on this going into danielballan/one-run-callbacks I will.

**Comment by danielballan** [comment]
Before I forget, maybe we should call `Path` `Trajectory` or something because we might want to reserve "Path" for https://matplotlib.org/api/path_api.html

**Comment by awalter-bnl** [comment]
The Travis errors are unrelated to this PR as none of them touch the specific files that have been changed here. (they appear to be test errors deep in the run-engine and associated with None-type objects from what I can tell).

**Comment by awalter-bnl** [comment]
closing this as I have opened it against  'danielballan:one-run-callbacks'under [PR # 13](https://github.com/danielballan/bluesky/pull/13)

**Pull request closed without merging**
