### PR TITLE
DOC minor, minor, minor typo

### PR DESCRIPTION
**Pull request by prjemian**
swapping the grammar here

### CODE REVIEW

**Comment by danielballan** [comment]
No documentation PR is too small to be deeply appreciated! :-D

**Comment by mrakitin** [comment]
Recycling to pick up #1153.

**Comment by mrakitin** [comment]
The tests on Travis passed for 3.5 and 3.6. The 2 other checks are not relevant.

**Comment by prjemian** [comment]
Apparently no details too small.

**Pull request merged**
