### PR TITLE
docstring fix

### PR DESCRIPTION
**Pull request by jrmlhermitte**
OCD fix
(maybe should also be `RE=RE`. also would suggest emphasizing that this is not necessary and `RE.subscribe` can be called after the fact as well)

### CODE REVIEW

**Comment by tacaswell** [comment]
It actually _must_ be `RE=RE` as it is a keyword-only arg!

**Comment by jrmlhermitte** [comment]
urgh yes you're right :-| oops!

**Comment by tacaswell** [comment]
Just noticed this is your first bluesky PR! :tada:

**Comment by jrmlhermitte** [comment]
:laughing:

**Pull request merged**
