### PR TITLE
Wip persistify

### PR DESCRIPTION
**Pull request by tacaswell**
This needs some docs and clean up.

Maybe worth hacking a bit so it introspects better in the RE.

### CODE REVIEW

**Comment by danielballan** [comment]
Why not just advertise `functools.partial` and avoid inventing another name? A `partial` object has pretty good introspection:

```python
In [12]: partial(count, [det])
Out[12]: functools.partial(<function count at 0x1088fcae8>, [SynGauss(name=det)])

In [13]: partial(count, detectors=[det], num=3)
Out[13]: functools.partial(<function count at 0x1088fcae8>, detectors=[SynGauss(name=det)], num=3)
```

**Comment by tacaswell** [comment]
Can you replace the values bound into `partial`

doing `__call__` as

```python
def __call__(self, **kwargs):
    kw = dict(self._kwargs)
    kw.update(kwrargs)
    return (yield from self._func(**kw))
```

might be useful?

Some people might also love if it did

```python
def __call__(self, **kwargs):
    self._kwargs.update(kwargs)

    return (yield from self._func(**self._kwargs))
```

**Comment by danielballan** [comment]
I see the case for that but I'm personally very excited by it. It could be hard to trace back the state of each parameter through time.

Is there still active interest in this PR?

**Comment by tacaswell** [comment]
`partial` is better.

**Pull request closed without merging**
