### PR TITLE
make RemoteDispatchers `_loop` public

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank for the doc fix, but can you actually fix this the other way and make `loop` public?

**Comment by CJ-Wright** [comment]
Sure it'll be in tomorrow.

**Comment by tacaswell** [comment]
This needs to be besade.

**Comment by CJ-Wright** [comment]
What does besade mean?

**Comment by danielballan** [comment]
Test failures are random and unrelated. Thanks, @CJ-Wright!

**Pull request merged**
