### PR TITLE
ENH: Add example for customized Olog callback

### PR DESCRIPTION
**Pull request by ericdill**
This is how I customized the logbook entries at CHX.  I am confident that this is not what everyone else will want, but it does serve as a template with which others could modify this to suit their needs.  Thoughts?

### CODE REVIEW

**Comment by tacaswell** [comment]
Can you move this into https://github.com/NSLS-II/bluesky/blob/master/bluesky/callbacks/olog.py and rebase?

**Comment by ericdill** [comment]
@tacaswell rebased and moved to olog.py.  Not sure if this is still terribly useful if you can just make a jinja template to do this.

**Comment by tacaswell** [comment]
This way is conceptually simpler (no templating, no function factories).
Has obvious path to add olog integration on other documents.

If this does not go here, it should go in examples some place.

**Comment by ericdill** [comment]
Ah ok, that makes sense.  If it makes sense for it to be in the library then let's just merge this in if it looks ok

**Pull request merged**
