### PR TITLE
MNT: fix invalid escape sequences in strings

### PR DESCRIPTION
**Pull request by pavoljuhas**
Fix invalid escape-sequence warnings from Python 3.6.

### CODE REVIEW

**Comment by danielballan** [comment]
Thanks. Just curious -- what changed in Python 3.6? I can't reproduce any warning:

```py
>>> import sys; sys.version_info
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
>>> fig_name = 'thing'
>>> import re
re.compile('^thing \\d+$')
# No warning?
```

**Comment by awalter-bnl** [comment]
I had a similar issue with an nslsii push [here](https://github.com/NSLS-II/nslsii/pull/46/commits/1bc2ddd0da72fb389bb2debf1e383e90011e1b45) recently. Locally it did not error out, but it did on Travis, not sure what made this issue suddenly start to be raised.

**Comment by pavoljuhas** [comment]
> Just curious -- what changed in Python 3.6? I can't reproduce any warning:

They turned on deprecation warnings for the tests.  I see the same with

```sh
$ python3.6 -Wall -c '"a\db"'
<string>:1: DeprecationWarning: invalid escape sequence \d
```

**Comment by danielballan** [comment]
Ah, makes sense.

**Comment by pavoljuhas** [comment]
The CI fails because this is branched off [failing master](https://travis-ci.org/NSLS-II/bluesky/builds/433740922).

I guess this will then wait for the master to be fixed?

**Comment by danielballan** [comment]
Oh, I'm behind the times! Yes, we'll re-run CI once master is sorted out.

**Comment by danielballan** [comment]
Power-cycled to re-run Travis now that `master` is passing CI.

**Comment by danielballan** [comment]
Thanks again @pavoljuhas! Clean-up PRs like this are very appreciated!

**Pull request merged**
