### PR TITLE
DOC: Draft a comparison with SPEC with @prjemian.

### PR DESCRIPTION
**Pull request by danielballan**
Distilling some thoughts that often come up verbally at tutorials
into a new page of the documentation.

### CODE REVIEW

**Comment by danielballan** [comment]
@dchabot -- You can a good slide on topic this back in the day. Any comments?

**Comment by danielballan** [comment]
Are there important differences in our handling of pseudomotors worth highlighting here? Or should I just mention it as a good thing about SPEC that we have tried to retain?

Good thought about a link to the data model.

**Comment by prjemian** [comment]
Good catch about the event model.  Very important new design component.
Allows for collection of asynchronous, uncoordinated data.

**Comment by danielballan** [comment]
I think this is good to go. I'll let @stuartcampbell pull the trigger.

**Comment by danielballan** [comment]
Disregard last comment. I forgot I had solicited some feedback that just came in, which I should now incorporate.

**Comment by danielballan** [comment]
OK, I think this is good to go.

**Pull request merged**
