### PR TITLE
Fix Bad #L line in spec callback

### PR DESCRIPTION
**Pull request by ericdill**
This solves the first of the three problems enumerated in #391 and should make the spec file writer immediately usable.

### CODE REVIEW

**Comment by ericdill** [comment]
ugh i hate it when I have a typo in my git commit title line. am I fussy enough to fix it?

**Comment by ericdill** [comment]
attn @dan

**Comment by danielballan** [comment]
Great. Thanks again for digging into this.

**Comment by ericdill** [comment]
I would normally advocate for testing this on a beamline before merging it in, but since the spec callback is broken in master anyway, I suppose this can't really make it any worse! *crosses fingers*

**Comment by danielballan** [comment]
I'll swing by CHX and give it a try early tomorrow.

**Comment by ericdill** [comment]
Could they install master themselves and try it and save you a trip over there?

**Comment by danielballan** [comment]
@lwiegart? @yugangzhang? Would you try updating bluesky (in an hour or so, when the new build becomes available) and let us know if this works?

**Comment by yugangzhang** [comment]
@danielballan I just update bluesky, but get errors:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/xf11id/.ipython/profile_collection/startup/00-startup.py in <module>()
      8 from bluesky import qt_kicker
      9 qt_kicker.install_qt_kicker()
---> 10 from databroker import DataBroker as db, get_events, get_images, get_table, get_fields, restream, process
     11 
     12 from epics import caput, caget

ImportError: cannot import name 'restream'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/xf11id/.ipython/profile_collection/startup/30-user.py in <module>()
      2 from ophyd import EpicsMotor
      3 from epics import caput
----> 4 from filestore import RawHandler
      5 
      6 class ReversedEpicsMotor(EpicsMotor):

ImportError: cannot import name 'RawHandler'
/home/xf11id/conda_envs/collection/lib/python3.5/site-packages/filestore/retrieve.py:15: UserWarning: Do not import filestore.retrieve, import filestore.api instead
```

**Comment by danielballan** [comment]
It looks like you have downgraded the databroker and/or filestore.

**Comment by yugangzhang** [comment]
I just did ```conda update bluesky```
I will try to update databroker and/or filestore.

**Comment by ericdill** [comment]
Can you copy the output from the original `conda update bluesky`?

**Comment by yugangzhang** [comment]
```
(collection)xf11id@xf11id-ws1:~$ conda update bluesky
Fetching package metadata: ....
Solving package specifications: ......................................................................................................
Package plan for installation in environment /home/xf11id/conda_envs/collection:

The following packages will be UPDATED:

    tzlocal:         1.1.2-py35_1                  --> 1.1.2-py35_0                     

The following packages will be DOWNGRADED:

    bluesky:         0.4.3-py35_1                  --> 0.4.0rc2.post9-9_g425d932_py35   
    channelarchiver: 0.0.5.6-py35_1                --> 0.0.5.post6-6_gfac126f_npNonepy35
    databroker:      0.3.3-py35_0                  --> 0.3.1.post15-15_g786344a_py35    
    doct:            1.0.1-py35_0                  --> 1.0.0.post4-py35_0               
    filestore:       0.2.3-py35_0                  --> 0.2.2.post5-5_g3bc4a5f_py35      
    matplotlib:      1.5.1.post61-61_g513da02_py35 --> 1.5.1-np110py35_0                
    metadatastore:   0.3.2-py35_0                  --> 0.3.1-py35_0                     
    readline:        6.2.5-1                       --> 6.2-12                           
    tifffile:        0.7.0-np110py35_1             --> 0.3.1-np110py35_0                

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##############################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##############################################################################################################| 100%
(collection)xf11id@xf11id-ws1:~$ ./collection
```

**Comment by yugangzhang** [comment]
@danielballan 
```
(collection)xf11id@xf11id-ws1:~$ conda update filestore
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /home/xf11id/conda_envs/collection:
#
filestore                 0.2.2.post5     5_g3bc4a5f_py35    https://pergamon.cs.nsls2.local:8443/conda/nsls2/linux-64/filestore-0.2.2.post5-5_g3bc4a5f_py35.tar.bz2
(collection)xf11id@xf11id-ws1:~$ conda update databroker
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /home/xf11id/conda_envs/collection:
#
databroker                0.3.1.post15    15_g786344a_py35    https://pergamon.cs.nsls2.local:8443/conda/nsls2/linux-64/databroker-0.3.1.post15-15_g786344a_py35.tar.bz2
(collection)xf11id@xf11id-ws1:~$ 
```

It seems like that databroker and filestore are the latest version.

**Comment by ericdill** [comment]
Right, so I take it you see how that command downgraded a ton of packages?  In the future, you can avoid this by doing `conda update <package> --no-deps` which will only affect <package>. In this case, `conda update bluesky --no-deps` would have avoided this.  Also please ask questions if you are unsure of something!

**Comment by ericdill** [comment]
what is in your `.condarc`?

**Comment by danielballan** [comment]
I can see how that is confusing, but please read the log you just posted above. See how databroker and others were downgraded?

The reason is that the "default" channel (nsls2) is conservative and thus out of date to what you guys are doing. So, because you did not provide the argument `-c nsls2-dev`, conda downgraded.

**Comment by danielballan** [comment]
I'll leave it to you @ericdill  -- thanks.

**Comment by ericdill** [comment]
Here's what you need to do @yugangzhang ...


`conda update collection -c nsls2-tag`

then

`conda update bluesky -c nsls2-dev`

**Comment by yugangzhang** [comment]
@danielballan  and @ericdill  I saw the degradation problem. 
@ericdill there is nothing in vi ~/.condarc, I guess we should make the default not so conservative to degrade the packages.

@ericdill
 ```(collection)xf11id@xf11id-ws1:~$ conda update collection -c nsls2-tag
Error: package 'collection' is not installed in /home/xf11id/conda_envs/collection
```

but i have
```
(collection)xf11id@xf11id-ws1:~$ conda info -e
# conda environments:
#
collection            *  /home/xf11id/conda_envs/collection
collection2              /home/xf11id/conda_envs/collection2
analysis                 /opt/conda_envs/analysis
root                     /opt/conda
```

**Comment by ericdill** [comment]
Ok, then just do `conda install collection -c nsls2-tag`

**Comment by ericdill** [comment]
collection, in this case, is [this metapackage] (https://github.com/NSLS-II/auto-build-tagged-recipes/blob/master/pyall/collection-2016_01/meta.yaml), not the conda environment

**Comment by danielballan** [comment]
> I guess we should make the default not so conservative to degrade the packages.

Agreed. Remind me and we can recalibrate this next time I visit.

**Comment by yugangzhang** [comment]
@ericdill and @danielballan  thanks! all the degraded packages are updated. 
I just did a scan in collection, it works.

**Comment by danielballan** [comment]
Great. Let us know when you can about whether pymca is reading the SPEC files happily now.

**Comment by yugangzhang** [comment]
I just looked at speck file in pymca for the latest scan. It plots correctly. Great!

**Comment by ericdill** [comment]
Just because I'm paranoid, can you copy the contents of the spec file for the last scan into this PR?

**Comment by yugangzhang** [comment]
```
79293 
79294 
79295 #S 12841 dscan diff_yh -0.01 0.01 (3,) 
79296 #D 2016-03-21 17:15:11.681528
79297 #T -1 (Seconds)
79298 #P0 -inf -inf -inf -inf
79299 #N 8
79300 #L diff_yh    Epoch  Seconds  xray_eye3_stats1_total  xray_eye3_stats2_total  xray_eye3_stats3_total  xray_eye3_stats4_total  xray_ey      e3_stats5_total
79301 -8.90554  1458594916.5054994 -1 20871.0 2778.0 245921.0 19694.0 11684401.0
79302 -8.89708  1458594920.0270674 -1 20720.0 2837.0 247094.0 19949.0 11703664.0
79303 -8.890540000000001  1458594923.153153 -1 20787.0 2791.0 246239.0 19672.0 11683347.0
79304 -8.883780000000002  1458594926.4058714 -1 20676.0 2785.0 245269.0 19810.0 11683735.0
```

**Comment by ericdill** [comment]
Perfect. Thanks.

**Pull request merged**
