### PR TITLE
ENH: Add inject_md_wrapper and inject_md_decorator.

### PR DESCRIPTION
**Pull request by danielballan**
Example of where this is useful:

```python
inject_md_wrapper(multi_run_plan, {'last_dark_frame_uid': '...'})
```

### CODE REVIEW

**Comment by tacaswell** [comment]
Should we be using this all over the place in the default plans?

**Comment by danielballan** [comment]
Interesting suggestion, but I don't think so. This is a tool for injecting md into a plan from some third party that may or may not be exposing an md kwarg. But it is good that bluesky plans all have an md kwarg.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Jun 9, 2016 at 8:21 PM -0400, "Thomas A Caswell" <notifications@github.com<mailto:notifications@github.com>> wrote:


Should we be using this all over the place in the default plans?

**Comment by danielballan** [comment]
Actually I think you are right, @tacaswell. Notice that the built-in plans are mostly not using the stub plans (e.g., we use `Msg('set', ...)` instead of `abs_set(...)`) because I wrote the stubs last. If they turn out to be a good idea, we can do the refactor and test that the message sequences are exactly the same.

**Comment by tacaswell** [comment]
Will merge this now, refactor later.

**Pull request merged**
