### PR TITLE
remove np sanitize from ZMQ publisher

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@NSLS-II/dama ready for review!

**Comment by CJ-Wright** [comment]
We need to remove it because it would mutate the docs which is a no-no with the ``doct`` returns from the databroker. I'm not certain why it was there in the first place

**Comment by tacaswell** [comment]
It is the serializer's problem to deal with numpy arrays.

This is here as a legacy thing before we had really sorted out who was responsible for dealing converting numpy arrays -> bytes.   If we convert to lists pre-emptively it means that serializers can not be smart if they want to be.

**Comment by danielballan** [comment]
Thanks @CJ-Wright for the improvement, @mrakitin for asking good questions that prompted a better public record of this change, and @tacaswell for providing context.

**Pull request merged**
