### PR TITLE
ENH: add print_summary_wrapper

### PR DESCRIPTION
**Pull request by tacaswell**
Print a nice summary of the plan as it goes by.

### CODE REVIEW

**Comment by danielballan** [comment]
Could you slap a smoke test on this?

**Comment by tacaswell** [comment]
huh, I thought print_summary already had a test.

**Comment by danielballan** [comment]
Seems like it does, but my codecoverage browser plugin in show that this *wrapper* function does not. Also, please add a entry to the block of `make_decorator` calls (also in plans.py) and add an entry to the table of Stub Plans (doc/source/plan.rst).

**Comment by tacaswell** [comment]
But the existing `print_summary` is implemented in terms of the wrapper

**Comment by danielballan** [comment]
```
$ git grep bluesky/tests/ -e "print_summary"
$
```

**Comment by danielballan** [comment]
I'll leave this un-documented for now because we probably want to add other variants and I don't want to lock the naming in hard just yet. Also, it's not clear to me if `plan_tools.py` vs `plans.py` is a useful distinction or if we should just move this stuff into `plans.py`. (There isn't much in `plan_tools.py`.)

**Pull request merged**
