### PR TITLE
PERF: asyncio.sleep(0) is enough to relinquish control.

### LINKED ISSUE #506: Replace the asyncio.sleep in the _run loop with something more efficient

### PR DESCRIPTION
**Pull request by danielballan**
Closes #506

### CODE REVIEW

**Comment by tacaswell** [comment]
huh, looks like the thread executor does not execute correctly with a 0 sleep...

**Comment by klauer** [comment]
Hmm, only one test fails on 3.4 and 6 fail on 3.5. 

Is the issue report in python/asyncio not accurate or did I/we misinterpret it?

**Comment by arkilic** [comment]
Seems like bunch of asserts failing, I think your interpretation is correct

**Comment by tacaswell** [comment]
Restarted now that we have removed the thread pool.

**Comment by klauer** [comment]
Passes! 👍

**Comment by danielballan** [comment]
Huh. I don't have a precise understanding of why. Do you?

**Comment by tacaswell** [comment]
because although the sleep(0) is enough for asyncio to context switch, it is not enough to context switch the threads.  Putting a non-zero sleep in is enough to (almost always) ensure that the thread context switch happens and the event callbacks to process.

**Comment by danielballan** [comment]
I see. I'm satisfied. Merging.

**Pull request merged**
