### PR TITLE
TST: Yet another world-weary attempt to fix intermittent ramp plan failures.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by tacaswell** [comment]
I am :-1: on this

**Comment by danielballan** [comment]
It fails about 1/3 of the time these days. Can you think of a way that we can guarantee that the inner plan will be run X times?

**Comment by tacaswell** [comment]
I am :+1: on my changes, but someone else should review them to be merged.

**Comment by danielballan** [comment]
Glorious. Thanks!

**Pull request merged**
