### PR TITLE
Fix cb exceptions and tests; increase metadata test coverage

### PR DESCRIPTION
**Pull request by danielballan**
This is a bit of a hodgepodge -- see commit msgs for details.

Note that `RE.ignore_callback_exceptions`, a boolean flag, has never actually worked until now. Sorry, @klauer.

### CODE REVIEW

**Comment by klauer** [comment]
Thought I had been using it incorrectly or something - I had `catch_exceptions` decorators in place of that strewn about to help debug...

**Comment by danielballan** [comment]
We had a test covering it, but the test was wrong. Tricky!

**Comment by danielballan** [comment]
The `test_post_run` test has always been broken, but we're only now seeing it because the RunEngine/Dispatcher are now propagating callback errors.

It's still broken, but the problem is *definitely* confined to `post_run` specifically and *possibly* just a problem with the test code itself.

I'd like to get this merged for all the API changes and address the pre-existing issue with `test_post_run` separately. I marked the test a Known Failure in the latest commit.

**Comment by klauer** [comment]
A+, would click merge again. Thanks, @danielballan.

**Pull request merged**
