### PR TITLE
ENH: Add install_nb_kicker for LivePlot in notebooks.

### LINKED ISSUE #538: LivePlot with nbAgg does not live-update
Leaving this here to lure @tacaswell. The people are [clamoring](https://github.com/NSLS-II/Bug-Reports/issues/131) for it.

### PR DESCRIPTION
**Pull request by danielballan**
nbkicker

The hard part of this commit was written by @tacaswell.

attn @brunoseivam
Closes #538 
Partly addresses https://github.com/NSLS-II/Bug-Reports/issues/131

### CODE REVIEW

**Comment by tacaswell** [comment]
It is very odd that the 'Figure 1' does not show up until the very end.

**Comment by danielballan** [comment]
I noticed that too.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Wed, Aug 17, 2016 at 1:30 PM -0400, "Thomas A Caswell" <notifications@github.com<mailto:notifications@github.com>> wrote:


It is very odd that the 'Figure 1' does not show up until the very end.

**Comment by klauer** [comment]
Nice! 👍

**Comment by hhslepicka** [comment]
Sweet! :+1:
Now just missing the live table! :stuck_out_tongue_winking_eye:

**Comment by tacaswell** [comment]
Can we call this `install_foot_cannon`?

**Comment by tacaswell** [comment]
@hhslepicka while testing to develop this, live table 'just worked'.

**Comment by danielballan** [comment]
I still don't understand the LiveTable issue at all. It has definitely worked for me in the past at the "Daron and Dan show" tutorials.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Wed, Aug 17, 2016 at 6:28 PM -0400, "Thomas A Caswell" <notifications@github.com<mailto:notifications@github.com>> wrote:


@hhslepicka<https://github.com/hhslepicka> while testing to develop this, live table 'just worked'.

**Comment by danielballan** [comment]
Though I should hasten to add that (as I posted elsewhere) I have also been able to reproduce the issue. Can anyone reproduce the issue on current master?

Get Outlook for iOS<https://aka.ms/o0ukef>




On Wed, Aug 17, 2016 at 6:28 PM -0400, "Thomas A Caswell" <notifications@github.com<mailto:notifications@github.com>> wrote:


@hhslepicka<https://github.com/hhslepicka> while testing to develop this, live table 'just worked'.

**Comment by danielballan** [comment]
bump @hhslepicka any word on whether you can still reproduce LiveTable's failure to refresh?

**Comment by hhslepicka** [comment]
I can confirm that everything is working after the install_nb_kicker. I tested it in a virtual machine with the bluesky Mover and SynGauss as the detector and it works.
👍

**Pull request merged**
