### PR TITLE
ENH: pass mappings into logbook_cb_factory

### PR DESCRIPTION
**Pull request by tacaswell**
This allows customization based on the 'plan_name' field of the
RunStart.

attn @NSLS-II-CHX

### CODE REVIEW

**Comment by danielballan** [comment]
Add a smoke test?

**Comment by klauer** [comment]
:+1: Somewhat related while I'm thinking about it: I'd like to see some way to keep a logbook entry open for appending during a run. @tacaswell and I wanted to see if we could get support from Kunal or someone else (?) to do so.

**Comment by tacaswell** [comment]
Getting any test coverage on this is on my todo list for the weekend.

**Comment by danielballan** [comment]
I added tests. The actual enhancement code is Tom's, so I will merge.

**Pull request merged**
