### PR TITLE
MNT: Allow sample to be dict or string.

### PR DESCRIPTION
**Pull request by danielballan**
We tried to encourage people to use dictionaries to record their sample information by requiring that the field called 'sample' be a dict. This has turned out to be more annoying that helpful. Sometimes you just want sample to be a string. The error is off-putting and more likely causes users to simply avoid the metadata feature than to discover the joy of dictionaries.

This would require a corresponding change in metadataservice and the (so far unused) event-model repo. Is this OK with you @arkilic?

This one's for you, @lwiegart. (But I have come to agree.)

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1:

**Comment by arkilic** [comment]
Yes, if somebody wants to use a dict for sample information, we have amostra and sample uids.

**Comment by ericdill** [comment]
Any reason this cannot be merged?

**Comment by tacaswell** [comment]
Just being cautious and making sure that we have buy in from everyone.

**Comment by arkilic** [comment]
IMO, this is good to go

**Comment by ericdill** [comment]
Great.  Seems like this is a non controversial change.  Does metadataservice/metadataclient/event-model need to be updated before this change goes in?

**Comment by arkilic** [comment]
Yes, here https://github.com/NSLS-II/metadataservice/blob/master/metadataservice/schema/run_start.json#L12 and here https://github.com/NSLS-II/event-model/blob/master/event_model/schemas/run_start.json#L8

**Comment by ericdill** [comment]
I would imagine that metadataservice.schema should be replaced by the event-model project?  Same with bluesky.schema?

**Comment by arkilic** [comment]
Yes, @danielballan and I had this in mind but have not completed the integration yet. Also, we should apply this change to metadatastore as well

**Comment by danielballan** [comment]
I don't think this change affects metadatastore. Does it?

Let's aim to do the schema refactor during downtime.

Unless I am confused, this can go into bluesky at any point and nothing currently-deployed (metadatastore) will break.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Wed, Mar 9, 2016 at 5:58 AM -0800, "Arman Arkilic" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, @danielballan<https://github.com/danielballan> and I had this in mind but have not completed the integration yet. Also, we should apply this change to metadatastore as well

**Comment by arkilic** [comment]
You are right, mds does not need any changes: https://github.com/NSLS-II/metadatastore/blob/master/metadatastore/core.py#L488

**Comment by arkilic** [comment]
I changed it in metadataservice https://github.com/NSLS-II/metadataservice/pull/5.

Once this is merged, it is good to go @tacaswell or @hhslepicka

**Pull request merged**
