### PR TITLE
CLN: Remove unused and/or out-of-scope code.

### PR DESCRIPTION
**Pull request by danielballan**
- The hardware_checklist will be shipped separately (if used at all).
- The standard_config does not actually do much anymore and can be replaced by the documented example http://nsls-ii.github.io/beamline-configuration.html#example-configuration-file or, as discussed, a [separate package or gist](https://github.com/NSLS-II/wishlist/issues/101).

Although the end result is standard_config.py now fully removed, I disassembled it piece by piece in individual commits to be sure to all important functionality was moved elsewhere. See commit messages for details.

### CODE REVIEW

**Comment by ericdill** [comment]
Is updating the conda-recipe in scope for this cleanup?

**Comment by danielballan** [comment]
Is it if you want to add a commit. What needs to be updated?

**Comment by ericdill** [comment]
The following are currently imported in modules but not in run/requirements of the meta.yaml

    - boltons (plans.py and simple_scans.py)
    - pyepics (suspenders.py)
    - metadataclient (register_mds.py)

The following are imported in callbacks and should probably be included with the repackaging of callbacks, but are fine to leave out for now:

    - scipy (scientific_callbacks.py)
    - databroker (broker_callbacks.py)
    - doct (broker_callbacks.py)
    - xray-vision (broker_callbacks.py)
    - tifffile (broker_callbacks.py)
    - IPython (callbacks/olog.py)
    - pyOlog (callbacks/olog.py)

I would also like to remove `np{{ np }}` from the build/string in the meta.yaml. Since bluesky is not compiled against numpy such an addition is not required.

Thoughts?

**Comment by danielballan** [comment]
Thanks for that thorough review.

I added boltons in a commit. All the rest I would consider optional deps that, yes, should probably be repackaged when the callbacks are moved off into separate repos. Although we usually include optional deps in conda recipes, I'd would rather wait in this case.

I also removed the numpy section of the build string -- good call.

**Comment by ericdill** [comment]
Great. Thanks for the addition of boltons and the removal of the numpy build string.  Those were the two "high priority" items as far as I was concerned.  I am :+1: with the rest of what you said.

Just for my own information (mostly so I keep the packages building correctly) I would imagine metadataclient will get included once the service is deployed and pyepics maybe once suspenders is working again?

**Comment by danielballan** [comment]
I think we will [move register_mds (or similar) into metadatastore/metadataclient](https://github.com/NSLS-II/bluesky/issues/189) or perhaps just include it in the beamline config explicitly.

**Comment by danielballan** [comment]
The suspenders might move to ophyd.... unclear. Might be more obvious once the suspenders machinery is rewritten.

**Comment by danielballan** [comment]
[Sorry for the stream-of-consciouness messages...] Travis is failing consistently on two of the vertical integration tests, but I can't reproduce those failures locally.

**Comment by ericdill** [comment]
Thanks for the info. Sorry I was not already aware of the issue you linked to!  This PR has a hearty :+1: from me. I like deleting code. It's that much less maintenance burden :-D

**Comment by ericdill** [comment]
I was unable to replicate the failures with the metadatastore 3.2 conda package, but was able to replicate the failure with metadatastore master.  Travis is running metadatastore master, so I am reasonably confident that this is the problem.  Which version of mds are you running locally?

**Comment by ericdill** [comment]
```
$ coverage run run_tests.py -k vertical_integration
pytest arguments: ['-v', '-vrxs', '-k', 'vertical_integration']
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.5.1, pytest-2.8.5, py-1.4.31, pluggy-0.3.1 -- /home/edill/miniconda/envs/bs35/bin/python
cachedir: .cache
rootdir: /home/edill/dev/python/bluesky, inifile: 
collected 78 items 

bluesky/tests/test_vertical_integration.py::test_scan_and_get_data FAILED
bluesky/tests/test_vertical_integration.py::test_post_run FAILED
bluesky/tests/test_vertical_integration.py::test_verify_files_saved PASSED

===================================================================================== FAILURES =====================================================================================
______________________________________________________________________________ test_scan_and_get_data ______________________________________________________________________________

    def test_scan_and_get_data():
        try:
            import metadatastore
            from databroker import DataBroker as db
            from bluesky.global_state import gs
        except ImportError as ie:
            raise pytest.skip('skipping because some libary is unavailable\n'
                              'ImportError:  is:{}'.format(ie))
        uid = gs.RE(stepscan(det, motor), group='foo', beamline_id='testing',
                 config={})
    
>       hdr = db[uid]

bluesky/tests/test_vertical_integration.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../miniconda/envs/bs35/lib/python3.5/site-packages/databroker/databroker.py:158: in __getitem__
    return search(key)
../../../miniconda/envs/bs35/lib/python3.5/functools.py:743: in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
../../../miniconda/envs/bs35/lib/python3.5/site-packages/databroker/databroker.py:146: in _
    return [search(k) for k in key]
../../../miniconda/envs/bs35/lib/python3.5/site-packages/databroker/databroker.py:146: in <listcomp>
    return [search(k) for k in key]
../../../miniconda/envs/bs35/lib/python3.5/functools.py:743: in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

key = 'b93178fd-7eb5-4d6e-8cde-58f98558df82'

    @search.register(str)
    @search.register(six.text_type)
    # py2: six.string_types = (basestring,)
    # py3: six.string_types = (str,)
    # so we need to just grab the only element out of this
    @search.register(six.string_types,)
    def _(key):
        logger.info('Interpreting key = %s as a str' % key)
        results = None
        if len(key) >= 36:
            # Interpret key as a uid (or the few several characters of one).
            logger.debug('Treating %s as a full uuid' % key)
            results = list(find_run_starts(uid=key))
            logger.debug('%s runs found for key=%s treated as a full uuid'
                         % (len(results), key))
        if not results == 0:
            # No dice? Try searching as if we have a partial uid.
            logger.debug('Treating %s as a partial uuid' % key)
            gen = find_run_starts(uid={'$regex': '{0}.*'.format(key)})
            results = list(gen)
        if not results:
            # Still no dice? Bail out.
>           raise ValueError("No such run found for key=%s" % key)
E           ValueError: No such run found for key=b93178fd-7eb5-4d6e-8cde-58f98558df82

../../../miniconda/envs/bs35/lib/python3.5/site-packages/databroker/databroker.py:131: ValueError
__________________________________________________________________________________ test_post_run ___________________________________________________________________________________

    def test_post_run():
        try:
            import databroker
            from bluesky.global_state import gs
            from bluesky.broker_callbacks import post_run
        except ImportError as ie:
            raise pytest.skip('skipping because some libary is unavailable\n'
                              'ImportError:  is:{}'.format(ie))
        output = defaultdict(list)
        def do_nothing(doctype, doc):
            output[doctype].append(doc)
    
        gs.RE.ignore_callback_exceptions = False
    
>       gs.RE(stepscan(det, motor), subs={'stop': [post_run(do_nothing)]})

bluesky/tests/test_vertical_integration.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
bluesky/run_engine.py:555: in __call__
    raise exc
../../../miniconda/envs/bs35/lib/python3.5/asyncio/tasks.py:239: in _step
    result = coro.send(None)
bluesky/run_engine.py:736: in _run
    raise err
bluesky/run_engine.py:710: in _run
    self._genstack[-1].throw(e)
bluesky/examples.py:591: in stepscan
    yield Msg('close_run')
bluesky/run_engine.py:706: in _run
    response = yield from coro(msg)
bluesky/run_engine.py:903: in _close_run
    yield from self.emit(DocumentNames.stop, doc)
../../../miniconda/envs/bs35/lib/python3.5/asyncio/coroutines.py:206: in coro
    res = func(*args, **kw)
bluesky/run_engine.py:1461: in emit
    self.dispatcher.process(name, doc)
bluesky/run_engine.py:1477: in process
    exceptions = self.cb_registry.process(name, name.name, doc)
bluesky/utils.py:156: in process
    func(*args, **kwargs)
bluesky/utils.py:237: in __call__
    return mtd(*args, **kwargs)
bluesky/broker_callbacks.py:83: in f
    start = run_start_given_uid(uid)
../metadatastore/metadatastore/commands.py:82: in run_start_given_uid
    return _DB_SINGLETON.run_start_given_uid(uid)
../metadatastore/metadatastore/mds.py:169: in run_start_given_uid
    self._RUNSTART_CACHE)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

uid = '98b16d0d-aea7-47d1-831f-f481c9c52898'
run_start_col = Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'mds'), 'run_start')
run_start_cache = LRU(max_size=1000, on_miss=None, values={})

    def run_start_given_uid(uid, run_start_col, run_start_cache):
        """Given a uid, return the RunStart document
    
        Parameters
        ----------
        uid : str
            The uid
    
        run_start_col : pymongo.Collection
            The collection to search for documents
    
        run_start_cache : MutableMapping
            Mutable mapping to serve as a local cache
    
        Returns
        -------
        run_start : doc.Document
            The RunStart document.
    
        """
        try:
            return run_start_cache[uid]
        except KeyError:
            pass
    
        run_start = run_start_col.find_one({'uid': uid})
    
        if run_start is None:
>           raise NoRunStart("No runstart with uid {!r}".format(uid))
E           metadatastore.core.NoRunStart: No runstart with uid '98b16d0d-aea7-47d1-831f-f481c9c52898'

../metadatastore/metadatastore/core.py:196: NoRunStart
------------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------------
Run aborted
No runstart with uid '98b16d0d-aea7-47d1-831f-f481c9c52898'
================================================================= 75 tests deselected by '-kvertical_integration' ==================================================================
================================================================ 2 failed, 1 passed, 75 deselected in 3.62 seconds =================================================================
```

**Comment by danielballan** [comment]
Fixed, I hope. See commit.

**Comment by ericdill** [comment]
LGTM. Would like a second set of reviewer eyes.  attn @klauer @dchabot @tacaswell

**Comment by klauer** [comment]
I've been sitting next to @danielballan for some of this. Looks fine to me.

**Comment by ericdill** [comment]
Minor change to the vertical_integration test. Would provide a less noisy skip message if you do this:

```python
def setup_module(module):
    try:
        from metadatastore.utils.testing import mds_setup
    except ImportError as ie:
        raise pytest.skip('ImportError: {0}'.format(ie))
    else:
        mds_setup()
        register_mds(gs.RE)
```

That way only one skip error message is raised and it is for the whole module.  That being said, do it if you would like and totally fine if you are ambivalent about it.  Mostly mentioning it because I just figured out that you can raise pytest.skip from the setup_module function and it skips the whole module.

**Comment by ericdill** [comment]
Thanks for the code clean up @danielballan .  Nontrivial task that is not made any easier by some jerk changing the mds testing api under you.

**Comment by tacaswell** [comment]
@ericdill That is nifty that you can skip the whole module like that.

**Pull request merged**
