### PR TITLE
Fix typo in exception

### PR DESCRIPTION
**Pull request by ericdill**
In NSLS-II/Bug-Reports#80 Yugang posted some text which 
highlighted a typo in our Exception text. This fixes that

### CODE REVIEW

**Comment by tacaswell** [comment]
Why is tifffile missing again?

**Comment by ericdill** [comment]
Uh, what?

**Comment by ericdill** [comment]
Oh, travis is failing.  I didn't connect the dots to what you were saying since this is just a documentation change.  It looks like tifffile is not being installed on travis anywhere.  Maybe adding `conda install tifffile` somewhere would fix this problem.

**Comment by ericdill** [comment]
The change was the release of pims 0.3.3.  The last PR that was closed used 

```
    pims-v0.2.2.post228        |228_g4d6bc61_npNonepy35          99 KB  lightsource2
```

Now pims is being pulled from soft-matter
```
    pims:            0.3.3-py35_1       soft-matter 
```

The recipe on lightsource2 includes tifffile as a dependency.
```
package:
    name: pims
    version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
    git_url: https://github.com/soft-matter/pims.git
    git_rev: master

build:
    number: 0
    string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

requirements:
    build:
        - python
        - six
        - setuptools
        - tifffile

    run:
        - python
        - six
        - numpy
        - scipy
        - pillow
        - tifffile

test:
    imports:
        - pims

about:
    home: http://soft-matter.github.io/pims/
    license: BSD
```
The recipe on soft-matter does not.

```
package:
  name: pims
  version: "0.3.3"

source:
  git_url: https://github.com/soft-matter/pims
  git_tag: v0.3.3

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - slicerator >=0.9.4
    - six >=1.8
    - numpy >=1.7

  run:
    - python
    - slicerator >=0.9.4
    - six >=1.8
    - numpy >=1.7
    - scikit-image  # one of { scikit-image | matplotlib | scipy }
    - pillow

test:
  imports:
    - pims
    - pims.tests
    - pims.utils

about:
  home: https://github.com/soft-matter/pims
  license: BSD
  summary: 'Python Image Sequence'
```

**Comment by ericdill** [comment]
Will add a PR to fix this.  For now self-merging this typo in documentation change.

**Comment by tacaswell** [comment]
Thanks @danielballan

**Comment by ericdill** [comment]
...can't tell if that's sarcasm...

**Pull request merged**
