### PR TITLE
CI: tweak ramp plan test timings

### PR DESCRIPTION
**Pull request by tacaswell**
Maybe this will be more reliable on travis?

### CODE REVIEW

**Comment by danielballan** [comment]
To save you some time: both builds failed on `test_ramp_plan.py::test_timeout`

**Comment by danielballan** [comment]
We have six open PRs that have failed Travis because of this test. Should we just known-fail it until we can sort it out?

**Comment by tacaswell** [comment]
Ah, that is a different failure!

**Comment by danielballan** [comment]
🎉

**Pull request merged**
