### PR TITLE
ENH: Emit event stream that logs messages before processing them.

### PR DESCRIPTION
**Pull request by danielballan**
This breaks some tests that are not expecting the new event stream that it produces. Once people review the implementation I will go back and fix the tests.

This addresses one half of #126.

### CODE REVIEW

**Comment by tacaswell** [comment]
Look, real _meta_ data.

Bit concerned that the down-stream tooling is not good enough yet to cope with always having 2 event streams.

**Comment by danielballan** [comment]
Yeah this is for next cycle.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Mon, Mar 14, 2016 at 4:06 PM -0700, "Thomas A Caswell" <notifications@github.com<mailto:notifications@github.com>> wrote:


Look, real meta data.

Bit concerned that the down-stream tooling is not good enough yet to cope with always having 2 event streams.

**Comment by danielballan** [comment]
@tacaswell I think you came down against this because of performance concerns. What's your current feeling about this?

**Comment by tacaswell** [comment]
I am +0.  If it is easy to turn off we can address the performance issues when we see them.

**Comment by danielballan** [comment]
I think logging message streams will help us perform forensics on poorly-reported bugs at the beamlines. This might be especially important as we test out the plans refactor and see more frequent use of asynchronous event stream.

I'll fix the tests tomorrow....

**Comment by danielballan** [comment]
This can be done on the plan side with some `log_messages` preprocessor: `RE(log_messages(plan)))`. The RunEngine does not need to be involved, and involving it would add complexity in a couple places, plus a performance hit. Closing.

**Pull request closed without merging**
