### PR TITLE
Slider callback

### PR DESCRIPTION
**Pull request by CJ-Wright**
## Description
Add an image viewer with a slider.

## Motivation and Context
Now users can look through their stack of images as they are taking them

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@tacaswell @danielballan Is it possible to add a check button to toggle whether or not the gui updates to the latest image?

**Comment by danielballan** [comment]
Sure! Looks like you're already working on that.

**Comment by CJ-Wright** [comment]
Yes, and it caused a lot of problems, so I removed it pending guidance.

**Comment by danielballan** [comment]
There's a reason I haven't done it yet. :- ) It's possible but it's tricky to get right.

**Comment by CJ-Wright** [comment]
I'd also like to get some guidance on how to not have to keep replacing the slider every time I add an image.

**Comment by CJ-Wright** [comment]
@tacaswell This was the issue I was mentioning the other day and you said I didn't have enough calls to draw idle.

**Comment by CJ-Wright** [comment]
This will work nicely as a subclass of `Filler`.

**Pull request closed without merging**
